/*
  The site's mark: a flat, thick-stemmed capital M in the accent green.
  The art lives in public/brand-mark.svg (110×120, transparent),
  regenerated by scripts/build-mark-svg.py. `unoptimized` ships the
  SVG as-is.
*/

import Image from 'next/image'

export function Mark({ size = 16 } = {}) {
  return (
    <Image
      src="/brand-mark.svg"
      alt=""
      aria-hidden="true"
      width={Math.round(size)}
      height={Math.round(size * 1.16)}
      sizes={`${Math.round(size)}px`}
      priority
      unoptimized
      className="shrink-0 block"
    />
  )
}